### ISSUE TITLE
Reflect upcoming rename of Floating IP -> Reserved IP

### ISSUE THREAD

**Issue by CanRau** [pulumi/pulumi-digitalocean#318]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

DigitalOcean is going to rename Floating IPs to be called Reserved IPs from 16 June 2022 as [stated here in the docs](https://docs.digitalocean.com/products/networking/floating-ips/#upcoming-changes).

**Comment by stack72** [comment]
Hi @CanRau 

Thanks for this - hugely useful information! I went digging upstream and found this PR - https://github.com/digitalocean/terraform-provider-digitalocean/pull/830

I guess we will deprecate the old resource when it happens and add an alias to the new name so that it doesn't disrupt people!

I will keep an eye for this when it comes out :)

Paul
