### ISSUE TITLE
Add Postgres database attributes

### ISSUE THREAD

**Issue by linuxluigi** [pulumi/pulumi-digitalocean#679]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add a option to configure `work_mem` & `shared_buffers_percentage` for a Postgres cluster. Looks like the [Terraform provider](https://github.com/digitalocean/terraform-provider-digitalocean/blob/629bb3b8b4717cc2d6e96acf02207009d22790d7/vendor/github.com/digitalocean/godo/databases.go#L512) already support all the attributes from the DO API. It would be great to have more options for the Postgres cluster configuration.

If somebody tells where the changes are needed, I'm happy to contribute 🙂

### Affected area/feature

Properly Terraform bridge

**Comment by guineveresaenger** [comment]
Hi @linuxluigi - thank you for opening this issue.

Can you tell us a bit more about which Pulumi resource you'd like to be enhanced? I assume you're talking bout `digitalocean.DatabaseCluster` but if not, a resource token would be helpful here!

I checked with the [upstream documentation](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster) for a DO database cluster, postgres flavor, and there's no support for `work_mem` or `shared_buffers_percentage` yet. The vendor dependencies you've linked don't necessarily translate into full support on the resource.

Since this provider uses the TF provider as an upstream dependency, you'd see new features like this percolate into our provider shortly. You may want to [file a feature request upstream](https://github.com/digitalocean/terraform-provider-digitalocean/issues/new/choose) as well.

**Comment by linuxluigi** [comment]
Hey @guineveresaenger,
thanks for answering. 

I guess you are right, the resource would be `digitalocean.DatabaseCluster`.

For the Terraform provider I also created the same feature requests, as you suggests.

**Comment by linuxluigi** [comment]
The PR https://github.com/digitalocean/terraform-provider-digitalocean/pull/1139 which added the PostgreSQL configurations is merged and a new terraform release was build yesterday.

What need to be done to add this to the Pulumi provider?

**Comment by mikhailshilkov** [comment]
This is now available in 4.28.0 of the provider. https://www.pulumi.com/registry/packages/digitalocean/api-docs/databasepostgresqlconfig/#workmem_nodejs
