### ISSUE TITLE
Kubeconfig provider pattern floods DO console with API tokens

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi-digitalocean#78]
I was using [the example pattern for provisioning a k8s cluster and using that as a provider for k8s resources](https://github.com/pulumi/examples/blob/d617a14bb933a7f54710100210eb603e9c1558ae/digitalocean-ts-k8s/index.ts#L25-L36). The `certificate-authority-data` field does indeed change on every `pulumi update`, but unfortunately this creates a new access token for every update and floods the DO console with tokens (see screenshot). Not a huge deal but it would probably be better if the kubeconfig was cached somehow until it expired instead of getting a new one every time. My workaround was to cache it as a local file along with the `cluster.kubeConfigs[0].expiresAt` value.

<img width="610" alt="Screen Shot 2020-03-24 at 9 35 07 PM" src="https://user-images.githubusercontent.com/2671649/77502212-74bbf680-6e17-11ea-9a2e-a4254de4d48b.png">

**Comment by metral** [comment]
I've been using DOKS 1.16 and 1.17 this week, and have not experienced the issue with `certificate-authority-data` changing on `pulumi refresh` or `pulumi update`.

Per [DO engineers](https://www.digitalocean.com/community/questions/when-saving-kubernetes-config-from-doctl-with-an-existing-api-token-another-token-is-created-is-this-normal), newer versions of k8s (starting with 1.16) by default use DO Access Tokens instead of certificates for the admin user's kubeconfig.

DO automatically creates this token for the cluster admin's kubeconfig, and the token expires after 7 days. However, the `certificate-authority-data` has a default expiration of 20 years -- (this could be a new change for the ca data not changing?)-- for example, here's the `openssl x509` text output on a cluster's ca data created today:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1653 (0x675)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = DigitalOcean, CN = k8saas Cluster CA
        Validity
            Not Before: Jun  5 16:39:34 2020 GMT
            Not After : Jun  5 16:39:34 2040 GMT
        Subject: O = DigitalOcean, CN = k8saas Cluster CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
....
```

This [comment](https://www.digitalocean.com/community/questions/when-saving-kubernetes-config-from-doctl-with-an-existing-api-token-another-token-is-created-is-this-normal?answer=56396) indicates that you can form your own kubeconfig using a normal DO API token, and disregard the automatic one created by DO. Using your own API token over the automatic one created seems favorable as the automatic one is set to expire in 7 days.

The pulumi equivalent of using a user-provided DO API token in a kubeconfig can be done using the following, e.g. in TS:

```
// Manufacture a DO kubeconfig that uses a given API token.
//
// Note: this is slightly "different" than the default DOKS kubeconfig created
// for the cluster admin, which uses a new token automatically created by DO.
export function createTokenKubeconfig(
    cluster: digitalocean.KubernetesCluster,
    user: pulumi.Input<string>,
    apiToken: pulumi.Input<string>,
): pulumi.Output<any> {
    return pulumi.interpolate`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${cluster.kubeConfigs[0].clusterCaCertificate}
    server: ${cluster.endpoint}
  name: ${cluster.name}
contexts:
- context:
    cluster: ${cluster.name}
    user: ${cluster.name}-${user}
  name: ${cluster.name}
current-context: ${cluster.name}
kind: Config
users:
- name: ${cluster.name}-${user}
  user:
    token: ${apiToken}
`;
}
```

**Comment by AaronFriel** [comment]
Looks like per the above comment we can consider this fixed or with an appropriate workaround. We're tracking the upstream provider's behavior here.

If you find this issue and it isn't resolved, please create a new issue!

**Comment by jadengis** [comment]
@metral 's comment should be somewhere in the docs. The existing example in the pulumi examples of DOKS doesn't work for me. Eventually it starts failing with expired credentials.
