### ISSUE TITLE
Userdata script does not appear no be working

### ISSUE THREAD

**Issue by brpaz** [pulumi/pulumi-digitalocean#99]
Hello.

I am trying to execute an  "user data" script on the boot of my droplet but it´s not working. It looks like the script is not executed:

Here is my code sample code:

```ts

const userData = `
  #!/bin/bash
  touch test.txt
 `;

const droplet = new Droplet(dropletName, {
  image: "ubuntu-18-04-x64",
  region: Regions.FRA1,
  privateNetworking: true,
  size: DropletSlugs.Droplet512mb,
  userData: userData,
});
```

If I login into my droplet, I was expecting to see the file "test.txt" but it´s not there. Also not working with contents with "cloud-config" syntax.

What I am missing?

**Comment by brpaz** [comment]
Nevermind. It seems it was the indentation of the file.

**Comment by MaximeEvangeliste** [comment]
> Nevermind. It seems it was the indentation of the file.

What did you do to fix it?

**Comment by MaximeEvangeliste** [comment]
For anyone who would land here, the problem in my case was that I was doing something like this to create the script before passing it to the pulumi/digitalocean droplet object.

```ts
const script = `
#!/usr/bin/env sh
// ...rest of the commands
`;
```

and the output of that was something like  `"\n#!/usr/bin/env sh ..."` so the line break at the beginning was preventing the script from being recognized as a bash script and then nothing was getting executed.

So the fix was only to put the hash-bang language declaration at on the same line as the template string to avoid the insertion of the line break:

```js
const script = `#!/usr/bin/env sh
// ...rest of the commands
`;
```

would output something like this  `"#!/usr/bin/env sh ..."` and then everything runs fine on the provisioned server.
